package repository

import (
	"context"

	"github.com/Deevins/final-task-course-2-go-lang/auth/internal/model"
	"github.com/gojuno/minimock/v3"
)

// Code generated by minimock (simplified for local use). DO NOT EDIT.

// AuthRepositoryMock implements AuthRepository for tests.
type AuthRepositoryMock struct {
	ctrl             *minimock.Controller
	CreateUserFunc   func(ctx context.Context, user model.User) (model.User, error)
	GetUserByEmailFn func(ctx context.Context, email string) (model.User, error)
	GetUserByIDFn    func(ctx context.Context, id string) (model.User, error)
}

// NewAuthRepositoryMock returns a new AuthRepositoryMock.
func NewAuthRepositoryMock(ctrl *minimock.Controller) *AuthRepositoryMock {
	return &AuthRepositoryMock{ctrl: ctrl}
}

func (m *AuthRepositoryMock) CreateUser(ctx context.Context, user model.User) (model.User, error) {
	if m.CreateUserFunc == nil {
		m.ctrl.Fatalf("CreateUser mock is not set")
		return model.User{}, nil
	}
	return m.CreateUserFunc(ctx, user)
}

func (m *AuthRepositoryMock) GetUserByEmail(ctx context.Context, email string) (model.User, error) {
	if m.GetUserByEmailFn == nil {
		m.ctrl.Fatalf("GetUserByEmail mock is not set")
		return model.User{}, nil
	}
	return m.GetUserByEmailFn(ctx, email)
}

func (m *AuthRepositoryMock) GetUserByID(ctx context.Context, id string) (model.User, error) {
	if m.GetUserByIDFn == nil {
		m.ctrl.Fatalf("GetUserByID mock is not set")
		return model.User{}, nil
	}
	return m.GetUserByIDFn(ctx, id)
}
