// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ledger/v1/ledger.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Transaction) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Transaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Transaction) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Transaction) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Budget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Period        string                 `protobuf:"bytes,6,opt,name=period,proto3" json:"period,omitempty"`
	Month         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=month,proto3" json:"month,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Budget) Reset() {
	*x = Budget{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Budget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Budget) ProtoMessage() {}

func (x *Budget) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Budget.ProtoReflect.Descriptor instead.
func (*Budget) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *Budget) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Budget) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Budget) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Budget) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Budget) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Budget) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *Budget) GetMonth() *timestamppb.Timestamp {
	if x != nil {
		return x.Month
	}
	return nil
}

func (x *Budget) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Budget) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Report struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Period        string                 `protobuf:"bytes,4,opt,name=period,proto3" json:"period,omitempty"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	TotalIncome   float64                `protobuf:"fixed64,6,opt,name=total_income,json=totalIncome,proto3" json:"total_income,omitempty"`
	TotalExpense  float64                `protobuf:"fixed64,7,opt,name=total_expense,json=totalExpense,proto3" json:"total_expense,omitempty"`
	Currency      string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *Report) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Report) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Report) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Report) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *Report) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *Report) GetTotalIncome() float64 {
	if x != nil {
		return x.TotalIncome
	}
	return 0
}

func (x *Report) GetTotalExpense() float64 {
	if x != nil {
		return x.TotalExpense
	}
	return 0
}

func (x *Report) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTransactionRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *GetTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransactionRequest) Reset() {
	*x = UpdateTransactionRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionRequest) ProtoMessage() {}

func (x *UpdateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionRequest.ProtoReflect.Descriptor instead.
func (*UpdateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTransactionRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type DeleteTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionRequest) Reset() {
	*x = DeleteTransactionRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionRequest) ProtoMessage() {}

func (x *DeleteTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionRequest.ProtoReflect.Descriptor instead.
func (*DeleteTransactionRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{7}
}

func (x *ListTransactionsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListTransactionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTransactionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{8}
}

func (x *ListTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ListTransactionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{9}
}

func (x *TransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type CreateBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Budget        *Budget                `protobuf:"bytes,1,opt,name=budget,proto3" json:"budget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBudgetRequest) Reset() {
	*x = CreateBudgetRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBudgetRequest) ProtoMessage() {}

func (x *CreateBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBudgetRequest.ProtoReflect.Descriptor instead.
func (*CreateBudgetRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{11}
}

func (x *CreateBudgetRequest) GetBudget() *Budget {
	if x != nil {
		return x.Budget
	}
	return nil
}

type GetBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBudgetRequest) Reset() {
	*x = GetBudgetRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBudgetRequest) ProtoMessage() {}

func (x *GetBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBudgetRequest.ProtoReflect.Descriptor instead.
func (*GetBudgetRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{12}
}

func (x *GetBudgetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetBudgetRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type UpdateBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Budget        *Budget                `protobuf:"bytes,1,opt,name=budget,proto3" json:"budget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBudgetRequest) Reset() {
	*x = UpdateBudgetRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBudgetRequest) ProtoMessage() {}

func (x *UpdateBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBudgetRequest.ProtoReflect.Descriptor instead.
func (*UpdateBudgetRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateBudgetRequest) GetBudget() *Budget {
	if x != nil {
		return x.Budget
	}
	return nil
}

type DeleteBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBudgetRequest) Reset() {
	*x = DeleteBudgetRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBudgetRequest) ProtoMessage() {}

func (x *DeleteBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBudgetRequest.ProtoReflect.Descriptor instead.
func (*DeleteBudgetRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteBudgetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteBudgetRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ListBudgetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBudgetsRequest) Reset() {
	*x = ListBudgetsRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBudgetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBudgetsRequest) ProtoMessage() {}

func (x *ListBudgetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBudgetsRequest.ProtoReflect.Descriptor instead.
func (*ListBudgetsRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{15}
}

func (x *ListBudgetsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListBudgetsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListBudgetsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListBudgetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Budgets       []*Budget              `protobuf:"bytes,1,rep,name=budgets,proto3" json:"budgets,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBudgetsResponse) Reset() {
	*x = ListBudgetsResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBudgetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBudgetsResponse) ProtoMessage() {}

func (x *ListBudgetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBudgetsResponse.ProtoReflect.Descriptor instead.
func (*ListBudgetsResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{16}
}

func (x *ListBudgetsResponse) GetBudgets() []*Budget {
	if x != nil {
		return x.Budgets
	}
	return nil
}

func (x *ListBudgetsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type BudgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Budget        *Budget                `protobuf:"bytes,1,opt,name=budget,proto3" json:"budget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetResponse) Reset() {
	*x = BudgetResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetResponse) ProtoMessage() {}

func (x *BudgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetResponse.ProtoReflect.Descriptor instead.
func (*BudgetResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{17}
}

func (x *BudgetResponse) GetBudget() *Budget {
	if x != nil {
		return x.Budget
	}
	return nil
}

type CreateReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *Report                `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReportRequest) Reset() {
	*x = CreateReportRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReportRequest) ProtoMessage() {}

func (x *CreateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReportRequest.ProtoReflect.Descriptor instead.
func (*CreateReportRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{18}
}

func (x *CreateReportRequest) GetReport() *Report {
	if x != nil {
		return x.Report
	}
	return nil
}

type GetReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportRequest) Reset() {
	*x = GetReportRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportRequest) ProtoMessage() {}

func (x *GetReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportRequest.ProtoReflect.Descriptor instead.
func (*GetReportRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{19}
}

func (x *GetReportRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetReportRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type UpdateReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *Report                `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReportRequest) Reset() {
	*x = UpdateReportRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReportRequest) ProtoMessage() {}

func (x *UpdateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReportRequest.ProtoReflect.Descriptor instead.
func (*UpdateReportRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateReportRequest) GetReport() *Report {
	if x != nil {
		return x.Report
	}
	return nil
}

type DeleteReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReportRequest) Reset() {
	*x = DeleteReportRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReportRequest) ProtoMessage() {}

func (x *DeleteReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReportRequest.ProtoReflect.Descriptor instead.
func (*DeleteReportRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteReportRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteReportRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ListReportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportsRequest) Reset() {
	*x = ListReportsRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportsRequest) ProtoMessage() {}

func (x *ListReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportsRequest.ProtoReflect.Descriptor instead.
func (*ListReportsRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{22}
}

func (x *ListReportsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListReportsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListReportsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListReportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*Report              `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportsResponse) Reset() {
	*x = ListReportsResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportsResponse) ProtoMessage() {}

func (x *ListReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportsResponse.ProtoReflect.Descriptor instead.
func (*ListReportsResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{23}
}

func (x *ListReportsResponse) GetReports() []*Report {
	if x != nil {
		return x.Reports
	}
	return nil
}

func (x *ListReportsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *Report                `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{24}
}

func (x *ReportResponse) GetReport() *Report {
	if x != nil {
		return x.Report
	}
	return nil
}

type ImportTransactionsCsvRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsvContent    []byte                 `protobuf:"bytes,1,opt,name=csv_content,json=csvContent,proto3" json:"csv_content,omitempty"`
	HasHeader     bool                   `protobuf:"varint,2,opt,name=has_header,json=hasHeader,proto3" json:"has_header,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportTransactionsCsvRequest) Reset() {
	*x = ImportTransactionsCsvRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportTransactionsCsvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportTransactionsCsvRequest) ProtoMessage() {}

func (x *ImportTransactionsCsvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportTransactionsCsvRequest.ProtoReflect.Descriptor instead.
func (*ImportTransactionsCsvRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{25}
}

func (x *ImportTransactionsCsvRequest) GetCsvContent() []byte {
	if x != nil {
		return x.CsvContent
	}
	return nil
}

func (x *ImportTransactionsCsvRequest) GetHasHeader() bool {
	if x != nil {
		return x.HasHeader
	}
	return false
}

func (x *ImportTransactionsCsvRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ImportTransactionsCsvResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Imported      int32                  `protobuf:"varint,1,opt,name=imported,proto3" json:"imported,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportTransactionsCsvResponse) Reset() {
	*x = ImportTransactionsCsvResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportTransactionsCsvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportTransactionsCsvResponse) ProtoMessage() {}

func (x *ImportTransactionsCsvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportTransactionsCsvResponse.ProtoReflect.Descriptor instead.
func (*ImportTransactionsCsvResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{26}
}

func (x *ImportTransactionsCsvResponse) GetImported() int32 {
	if x != nil {
		return x.Imported
	}
	return 0
}

type ExportTransactionsCsvRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportTransactionsCsvRequest) Reset() {
	*x = ExportTransactionsCsvRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportTransactionsCsvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTransactionsCsvRequest) ProtoMessage() {}

func (x *ExportTransactionsCsvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTransactionsCsvRequest.ProtoReflect.Descriptor instead.
func (*ExportTransactionsCsvRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{27}
}

func (x *ExportTransactionsCsvRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ExportTransactionsCsvResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsvContent    []byte                 `protobuf:"bytes,1,opt,name=csv_content,json=csvContent,proto3" json:"csv_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportTransactionsCsvResponse) Reset() {
	*x = ExportTransactionsCsvResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportTransactionsCsvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTransactionsCsvResponse) ProtoMessage() {}

func (x *ExportTransactionsCsvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTransactionsCsvResponse.ProtoReflect.Descriptor instead.
func (*ExportTransactionsCsvResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{28}
}

func (x *ExportTransactionsCsvResponse) GetCsvContent() []byte {
	if x != nil {
		return x.CsvContent
	}
	return nil
}

var File_ledger_v1_ledger_proto protoreflect.FileDescriptor

const file_ledger_v1_ledger_proto_rawDesc = "" +
	"\n" +
	"\x16ledger/v1/ledger.proto\x12\tledger.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe1\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12;\n" +
	"\voccurred_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xff\x02\n" +
	"\x06Budget\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06period\x18\x06 \x01(\tR\x06period\x129\n" +
	"\n" +
	"month\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x05month\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x86\x02\n" +
	"\x06Report\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06period\x18\x04 \x01(\tR\x06period\x12=\n" +
	"\fgenerated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12!\n" +
	"\ftotal_income\x18\x06 \x01(\x01R\vtotalIncome\x12#\n" +
	"\rtotal_expense\x18\a \x01(\x01R\ftotalExpense\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\"T\n" +
	"\x18CreateTransactionRequest\x128\n" +
	"\vtransaction\x18\x01 \x01(\v2\x16.ledger.v1.TransactionR\vtransaction\"'\n" +
	"\x15GetTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"T\n" +
	"\x18UpdateTransactionRequest\x128\n" +
	"\vtransaction\x18\x01 \x01(\v2\x16.ledger.v1.TransactionR\vtransaction\"*\n" +
	"\x18DeleteTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"m\n" +
	"\x17ListTransactionsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"~\n" +
	"\x18ListTransactionsResponse\x12:\n" +
	"\ftransactions\x18\x01 \x03(\v2\x16.ledger.v1.TransactionR\ftransactions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"O\n" +
	"\x13TransactionResponse\x128\n" +
	"\vtransaction\x18\x01 \x01(\v2\x16.ledger.v1.TransactionR\vtransaction\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"@\n" +
	"\x13CreateBudgetRequest\x12)\n" +
	"\x06budget\x18\x01 \x01(\v2\x11.ledger.v1.BudgetR\x06budget\"A\n" +
	"\x10GetBudgetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"@\n" +
	"\x13UpdateBudgetRequest\x12)\n" +
	"\x06budget\x18\x01 \x01(\v2\x11.ledger.v1.BudgetR\x06budget\"D\n" +
	"\x13DeleteBudgetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"h\n" +
	"\x12ListBudgetsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"j\n" +
	"\x13ListBudgetsResponse\x12+\n" +
	"\abudgets\x18\x01 \x03(\v2\x11.ledger.v1.BudgetR\abudgets\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\";\n" +
	"\x0eBudgetResponse\x12)\n" +
	"\x06budget\x18\x01 \x01(\v2\x11.ledger.v1.BudgetR\x06budget\"@\n" +
	"\x13CreateReportRequest\x12)\n" +
	"\x06report\x18\x01 \x01(\v2\x11.ledger.v1.ReportR\x06report\"A\n" +
	"\x10GetReportRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"@\n" +
	"\x13UpdateReportRequest\x12)\n" +
	"\x06report\x18\x01 \x01(\v2\x11.ledger.v1.ReportR\x06report\"D\n" +
	"\x13DeleteReportRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"h\n" +
	"\x12ListReportsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"j\n" +
	"\x13ListReportsResponse\x12+\n" +
	"\areports\x18\x01 \x03(\v2\x11.ledger.v1.ReportR\areports\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\";\n" +
	"\x0eReportResponse\x12)\n" +
	"\x06report\x18\x01 \x01(\v2\x11.ledger.v1.ReportR\x06report\"^\n" +
	"\x1cImportTransactionsCsvRequest\x12\x1f\n" +
	"\vcsv_content\x18\x01 \x01(\fR\n" +
	"csvContent\x12\x1d\n" +
	"\n" +
	"has_header\x18\x02 \x01(\bR\thasHeader\";\n" +
	"\x1dImportTransactionsCsvResponse\x12\x1a\n" +
	"\bimported\x18\x01 \x01(\x05R\bimported\"=\n" +
	"\x1cExportTransactionsCsvRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"@\n" +
	"\x1dExportTransactionsCsvResponse\x12\x1f\n" +
	"\vcsv_content\x18\x01 \x01(\fR\n" +
	"csvContent2\x89\v\n" +
	"\rLedgerService\x12X\n" +
	"\x11CreateTransaction\x12#.ledger.v1.CreateTransactionRequest\x1a\x1e.ledger.v1.TransactionResponse\x12R\n" +
	"\x0eGetTransaction\x12 .ledger.v1.GetTransactionRequest\x1a\x1e.ledger.v1.TransactionResponse\x12X\n" +
	"\x11UpdateTransaction\x12#.ledger.v1.UpdateTransactionRequest\x1a\x1e.ledger.v1.TransactionResponse\x12S\n" +
	"\x11DeleteTransaction\x12#.ledger.v1.DeleteTransactionRequest\x1a\x19.ledger.v1.DeleteResponse\x12[\n" +
	"\x10ListTransactions\x12\".ledger.v1.ListTransactionsRequest\x1a#.ledger.v1.ListTransactionsResponse\x12I\n" +
	"\fCreateBudget\x12\x1e.ledger.v1.CreateBudgetRequest\x1a\x19.ledger.v1.BudgetResponse\x12C\n" +
	"\tGetBudget\x12\x1b.ledger.v1.GetBudgetRequest\x1a\x19.ledger.v1.BudgetResponse\x12I\n" +
	"\fUpdateBudget\x12\x1e.ledger.v1.UpdateBudgetRequest\x1a\x19.ledger.v1.BudgetResponse\x12I\n" +
	"\fDeleteBudget\x12\x1e.ledger.v1.DeleteBudgetRequest\x1a\x19.ledger.v1.DeleteResponse\x12L\n" +
	"\vListBudgets\x12\x1d.ledger.v1.ListBudgetsRequest\x1a\x1e.ledger.v1.ListBudgetsResponse\x12I\n" +
	"\fCreateReport\x12\x1e.ledger.v1.CreateReportRequest\x1a\x19.ledger.v1.ReportResponse\x12C\n" +
	"\tGetReport\x12\x1b.ledger.v1.GetReportRequest\x1a\x19.ledger.v1.ReportResponse\x12I\n" +
	"\fUpdateReport\x12\x1e.ledger.v1.UpdateReportRequest\x1a\x19.ledger.v1.ReportResponse\x12I\n" +
	"\fDeleteReport\x12\x1e.ledger.v1.DeleteReportRequest\x1a\x19.ledger.v1.DeleteResponse\x12L\n" +
	"\vListReports\x12\x1d.ledger.v1.ListReportsRequest\x1a\x1e.ledger.v1.ListReportsResponse\x12j\n" +
	"\x15ImportTransactionsCsv\x12'.ledger.v1.ImportTransactionsCsvRequest\x1a(.ledger.v1.ImportTransactionsCsvResponse\x12j\n" +
	"\x15ExportTransactionsCsv\x12'.ledger.v1.ExportTransactionsCsvRequest\x1a(.ledger.v1.ExportTransactionsCsvResponseBMZKgithub.com/Deevins/final-task-course-2-go-lang/ledger/internal/pb/ledger/v1b\x06proto3"

var (
	file_ledger_v1_ledger_proto_rawDescOnce sync.Once
	file_ledger_v1_ledger_proto_rawDescData []byte
)

func file_ledger_v1_ledger_proto_rawDescGZIP() []byte {
	file_ledger_v1_ledger_proto_rawDescOnce.Do(func() {
		file_ledger_v1_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ledger_v1_ledger_proto_rawDesc), len(file_ledger_v1_ledger_proto_rawDesc)))
	})
	return file_ledger_v1_ledger_proto_rawDescData
}

var file_ledger_v1_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_ledger_v1_ledger_proto_goTypes = []any{
	(*Transaction)(nil),                   // 0: ledger.v1.Transaction
	(*Budget)(nil),                        // 1: ledger.v1.Budget
	(*Report)(nil),                        // 2: ledger.v1.Report
	(*CreateTransactionRequest)(nil),      // 3: ledger.v1.CreateTransactionRequest
	(*GetTransactionRequest)(nil),         // 4: ledger.v1.GetTransactionRequest
	(*UpdateTransactionRequest)(nil),      // 5: ledger.v1.UpdateTransactionRequest
	(*DeleteTransactionRequest)(nil),      // 6: ledger.v1.DeleteTransactionRequest
	(*ListTransactionsRequest)(nil),       // 7: ledger.v1.ListTransactionsRequest
	(*ListTransactionsResponse)(nil),      // 8: ledger.v1.ListTransactionsResponse
	(*TransactionResponse)(nil),           // 9: ledger.v1.TransactionResponse
	(*DeleteResponse)(nil),                // 10: ledger.v1.DeleteResponse
	(*CreateBudgetRequest)(nil),           // 11: ledger.v1.CreateBudgetRequest
	(*GetBudgetRequest)(nil),              // 12: ledger.v1.GetBudgetRequest
	(*UpdateBudgetRequest)(nil),           // 13: ledger.v1.UpdateBudgetRequest
	(*DeleteBudgetRequest)(nil),           // 14: ledger.v1.DeleteBudgetRequest
	(*ListBudgetsRequest)(nil),            // 15: ledger.v1.ListBudgetsRequest
	(*ListBudgetsResponse)(nil),           // 16: ledger.v1.ListBudgetsResponse
	(*BudgetResponse)(nil),                // 17: ledger.v1.BudgetResponse
	(*CreateReportRequest)(nil),           // 18: ledger.v1.CreateReportRequest
	(*GetReportRequest)(nil),              // 19: ledger.v1.GetReportRequest
	(*UpdateReportRequest)(nil),           // 20: ledger.v1.UpdateReportRequest
	(*DeleteReportRequest)(nil),           // 21: ledger.v1.DeleteReportRequest
	(*ListReportsRequest)(nil),            // 22: ledger.v1.ListReportsRequest
	(*ListReportsResponse)(nil),           // 23: ledger.v1.ListReportsResponse
	(*ReportResponse)(nil),                // 24: ledger.v1.ReportResponse
	(*ImportTransactionsCsvRequest)(nil),  // 25: ledger.v1.ImportTransactionsCsvRequest
	(*ImportTransactionsCsvResponse)(nil), // 26: ledger.v1.ImportTransactionsCsvResponse
	(*ExportTransactionsCsvRequest)(nil),  // 27: ledger.v1.ExportTransactionsCsvRequest
	(*ExportTransactionsCsvResponse)(nil), // 28: ledger.v1.ExportTransactionsCsvResponse
	(*timestamppb.Timestamp)(nil),         // 29: google.protobuf.Timestamp
}
var file_ledger_v1_ledger_proto_depIdxs = []int32{
	29, // 0: ledger.v1.Transaction.occurred_at:type_name -> google.protobuf.Timestamp
	29, // 1: ledger.v1.Transaction.created_at:type_name -> google.protobuf.Timestamp
	29, // 2: ledger.v1.Transaction.updated_at:type_name -> google.protobuf.Timestamp
	29, // 3: ledger.v1.Budget.month:type_name -> google.protobuf.Timestamp
	29, // 4: ledger.v1.Budget.created_at:type_name -> google.protobuf.Timestamp
	29, // 5: ledger.v1.Budget.updated_at:type_name -> google.protobuf.Timestamp
	29, // 6: ledger.v1.Report.generated_at:type_name -> google.protobuf.Timestamp
	0,  // 7: ledger.v1.CreateTransactionRequest.transaction:type_name -> ledger.v1.Transaction
	0,  // 8: ledger.v1.UpdateTransactionRequest.transaction:type_name -> ledger.v1.Transaction
	0,  // 9: ledger.v1.ListTransactionsResponse.transactions:type_name -> ledger.v1.Transaction
	0,  // 10: ledger.v1.TransactionResponse.transaction:type_name -> ledger.v1.Transaction
	1,  // 11: ledger.v1.CreateBudgetRequest.budget:type_name -> ledger.v1.Budget
	1,  // 12: ledger.v1.UpdateBudgetRequest.budget:type_name -> ledger.v1.Budget
	1,  // 13: ledger.v1.ListBudgetsResponse.budgets:type_name -> ledger.v1.Budget
	1,  // 14: ledger.v1.BudgetResponse.budget:type_name -> ledger.v1.Budget
	2,  // 15: ledger.v1.CreateReportRequest.report:type_name -> ledger.v1.Report
	2,  // 16: ledger.v1.UpdateReportRequest.report:type_name -> ledger.v1.Report
	2,  // 17: ledger.v1.ListReportsResponse.reports:type_name -> ledger.v1.Report
	2,  // 18: ledger.v1.ReportResponse.report:type_name -> ledger.v1.Report
	3,  // 20: ledger.v1.LedgerService.CreateTransaction:input_type -> ledger.v1.CreateTransactionRequest
	4,  // 21: ledger.v1.LedgerService.GetTransaction:input_type -> ledger.v1.GetTransactionRequest
	5,  // 22: ledger.v1.LedgerService.UpdateTransaction:input_type -> ledger.v1.UpdateTransactionRequest
	6,  // 23: ledger.v1.LedgerService.DeleteTransaction:input_type -> ledger.v1.DeleteTransactionRequest
	7,  // 24: ledger.v1.LedgerService.ListTransactions:input_type -> ledger.v1.ListTransactionsRequest
	11, // 25: ledger.v1.LedgerService.CreateBudget:input_type -> ledger.v1.CreateBudgetRequest
	12, // 26: ledger.v1.LedgerService.GetBudget:input_type -> ledger.v1.GetBudgetRequest
	13, // 27: ledger.v1.LedgerService.UpdateBudget:input_type -> ledger.v1.UpdateBudgetRequest
	14, // 28: ledger.v1.LedgerService.DeleteBudget:input_type -> ledger.v1.DeleteBudgetRequest
	15, // 29: ledger.v1.LedgerService.ListBudgets:input_type -> ledger.v1.ListBudgetsRequest
	18, // 30: ledger.v1.LedgerService.CreateReport:input_type -> ledger.v1.CreateReportRequest
	19, // 31: ledger.v1.LedgerService.GetReport:input_type -> ledger.v1.GetReportRequest
	20, // 32: ledger.v1.LedgerService.UpdateReport:input_type -> ledger.v1.UpdateReportRequest
	21, // 33: ledger.v1.LedgerService.DeleteReport:input_type -> ledger.v1.DeleteReportRequest
	22, // 34: ledger.v1.LedgerService.ListReports:input_type -> ledger.v1.ListReportsRequest
	25, // 35: ledger.v1.LedgerService.ImportTransactionsCsv:input_type -> ledger.v1.ImportTransactionsCsvRequest
	27, // 36: ledger.v1.LedgerService.ExportTransactionsCsv:input_type -> ledger.v1.ExportTransactionsCsvRequest
	9,  // 37: ledger.v1.LedgerService.CreateTransaction:output_type -> ledger.v1.TransactionResponse
	9,  // 38: ledger.v1.LedgerService.GetTransaction:output_type -> ledger.v1.TransactionResponse
	9,  // 39: ledger.v1.LedgerService.UpdateTransaction:output_type -> ledger.v1.TransactionResponse
	10, // 40: ledger.v1.LedgerService.DeleteTransaction:output_type -> ledger.v1.DeleteResponse
	8,  // 41: ledger.v1.LedgerService.ListTransactions:output_type -> ledger.v1.ListTransactionsResponse
	17, // 42: ledger.v1.LedgerService.CreateBudget:output_type -> ledger.v1.BudgetResponse
	17, // 43: ledger.v1.LedgerService.GetBudget:output_type -> ledger.v1.BudgetResponse
	17, // 44: ledger.v1.LedgerService.UpdateBudget:output_type -> ledger.v1.BudgetResponse
	10, // 45: ledger.v1.LedgerService.DeleteBudget:output_type -> ledger.v1.DeleteResponse
	16, // 46: ledger.v1.LedgerService.ListBudgets:output_type -> ledger.v1.ListBudgetsResponse
	24, // 47: ledger.v1.LedgerService.CreateReport:output_type -> ledger.v1.ReportResponse
	24, // 48: ledger.v1.LedgerService.GetReport:output_type -> ledger.v1.ReportResponse
	24, // 49: ledger.v1.LedgerService.UpdateReport:output_type -> ledger.v1.ReportResponse
	10, // 50: ledger.v1.LedgerService.DeleteReport:output_type -> ledger.v1.DeleteResponse
	23, // 51: ledger.v1.LedgerService.ListReports:output_type -> ledger.v1.ListReportsResponse
	26, // 52: ledger.v1.LedgerService.ImportTransactionsCsv:output_type -> ledger.v1.ImportTransactionsCsvResponse
	28, // 53: ledger.v1.LedgerService.ExportTransactionsCsv:output_type -> ledger.v1.ExportTransactionsCsvResponse
	37, // [37:54] is the sub-list for method output_type
	20, // [20:37] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_ledger_v1_ledger_proto_init() }
func file_ledger_v1_ledger_proto_init() {
	if File_ledger_v1_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ledger_v1_ledger_proto_rawDesc), len(file_ledger_v1_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ledger_v1_ledger_proto_goTypes,
		DependencyIndexes: file_ledger_v1_ledger_proto_depIdxs,
		MessageInfos:      file_ledger_v1_ledger_proto_msgTypes,
	}.Build()
	File_ledger_v1_ledger_proto = out.File
	file_ledger_v1_ledger_proto_goTypes = nil
	file_ledger_v1_ledger_proto_depIdxs = nil
}
